#ifndef __DEFINES_H
#define __DEFINES_H

#define COLORS 3 // RGB
#define PANEL_SIZE 64
#define PANEL_AREA PANEL_SIZE * PANEL_SIZE
#define PANELS_HORIZONTAL 3
#define PANELS_VERTICAL 2
#define PANELS PANELS_HORIZONTAL * PANELS_VERTICAL

#endif
