#ifndef __DEFINES_H
#define __DEFINES_H

#define COLORS 3 // RGB
#define PANEL_SIZE 64
#define PANEL_AREA PANEL_SIZE * PANEL_SIZE
#define PANELS_HORIZONTAL 3
#define PANELS_VERTICAL 2
#define PANELS PANELS_HORIZONTAL * PANELS_VERTICAL
//#define SCREEN_WIDTH (64 * 16 * 2)
//#define SCREEN_HEIGHT (64 * 9 * 2)
//#define SCREEN_WIDTH (64 * 16)
//#define SCREEN_HEIGHT (64 * 9)
#define SCREEN_WIDTH (64 * PANELS_HORIZONTAL)
#define SCREEN_HEIGHT (64 * PANELS_VERTICAL)
#endif
